spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://postgres:5432/stockdb
    username: stockuser
    password: stockpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        "[format_sql]": false

  flyway:
    enabled: true
    locations: classpath:db/migration
 
logging:
  level:
    "[org.hibernate.SQL]": DEBUG
    "[org.hibernate.orm.jdbc.bind]": TRACE

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    prometheus:
      access: UNRESTRICTED
  metrics:
    tags:
      application: stock-system-backend